FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR /app

COPY CardValidation.sln ./
COPY CardValidation.Core/*.csproj CardValidation.Core/
COPY CardValidation.CoreTests/*.csproj CardValidation.CoreTests/
COPY CardValidation.Web/*.csproj CardValidation.Web/

RUN dotnet restore CardValidation.sln --verbosity detailed

COPY . ./

WORKDIR /app

RUN dotnet build

CMD ["dotnet", "run", "--project", "CardValidation.Web/CardValidation.Web.csproj", "--urls", "http://0.0.0.0:7135"]