FROM mcr.microsoft.com/dotnet/sdk:7.0

WORKDIR /app

COPY CardValidation.CoreTests/CardValidation.CoreTests.csproj CardValidation.CoreTests/
COPY CardValidation.Core/CardValidation.Core.csproj CardValidation.Core/
COPY CardValidation.Web/CardValidation.Web.csproj CardValidation.Web/

COPY . .

RUN dotnet restore CardValidation.CoreTests/CardValidation.CoreTests.csproj

WORKDIR /app/CardValidation.CoreTests/

RUN dotnet build 

RUN dotnet test --logger:trx

CMD ["dotnet", "test", "CardValidation.CoreTests/CardValidation.CoreTests.csproj"]