name: Run Tests

on:
  push:
    branches: [ main, ci-artifacts ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # use .NET 8

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --logger "trx;LogFileName=TestResults.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: '**/TestResults.trx'

